### ISSUE TITLE
highbitrate CI fix for DM900UHD

### ISSUE THREAD

**Issue by usingen** [opendreambox/opendreambox#3]
Please can you add high bitrate support with CA module for DM900? I have problem with decoding MTS package on ABS-2A (75E), they use TP with bitrate 90Mbps! Thank you!

**Comment by usingen** [comment]
![mts](https://user-images.githubusercontent.com/33194963/32413541-88a23e78-c213-11e7-958e-6badf8aed6ec.png)

Decoding picture on Telekanal Zvezda, MTS (75E), SR 45Msym/s!

**Comment by sreichholf** [comment]
This should be fixed now.
